application: ice-bloc-hdr
version: delta
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

libraries:
- name: django
  version: "1.2"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

## updates:
  ## Aug11, 07: amsr2 filename, https://gamma-dot-ice-bloc-hdr.appspot.com/
  ## epsilon: Jul13, 18, gibs time range to 2000, intro arc-sentinel
  ## gamma:   Jul18, 18: added compsite 3 days sentinel
  ## beta     Jul30  18: Fixes, overlay 4326
  ## delta    Oct07  18: prepare https

handlers:

## SINGLE FILES
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /google2b12855243d6bbb0.html
  static_files: static/google2b12855243d6bbb0.html
  upload: static/google2b12855243d6bbb0.html

- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /apple-touch-icon-precomposed\.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed.png

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /google861a6aca749963ad.html
  static_files: static/google861a6aca749963ad.html
  upload: static/google861a6aca749963ad.html

# ## MAPS
# - url: /zooms
#   static_dir: static/zooms
#   expiration: "1m"

## DATA
- url: /data
  static_dir: static/data
  # expiration: "7d"

## IMAGES
- url: /images
  static_dir: static/images
  expiration: "7d"

## ARTICLES
- url: /articles
  static_dir: static/articles
  expiration: "1m"

## SOURCE MAPS
- url: /static/(.*\.map)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.map)

## MARKDOWN
- url: /static/(.*\.md)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.md)


## FONTS
- url: /fonts
  static_dir: static/fonts
  expiration: "7d"

- url: /fonts/(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.eot)
  expiration: "7d"

- url: /fonts/(.*\.woff)
  mime_type: application/x-font-woff
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.woff)
  expiration: "7d"

- url: /fonts/(.*\.ttf)
  mime_type: font/truetype
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.ttf)
  expiration: "7d"

- url: /fonts/(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.(svg|svgz))
  expiration: "7d"


## STATIC FINAL
- url: /static
  static_dir: static
  expiration: "1d"

## SIMPLE CACHE
- url: /cache/.*
  script: cache.app

# ## EDGE CACHE
# - url: /remote-sensing/.*
#   script: edge-proxy.app

## ADMIN
  
## ALL OTHER
- url: .*
  script: main.app

## IGNORE
skip_files: |
 ^(.*/)?(
 (#.*#)|
 (.*~)|
 (.*\.sh)|
 (.*\.xcf)|
 (.*\.rar)|
 (.*\.zip)|
 (.*\.gz)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (js/compiler)|
 (dev/.*)|
 (static/debug/.*)|
 (static/stuff/.*)|
 (templates/debug/.*)|
 (tests/.*)|
 (docs/.*)|
 (.*\.markdown)|
 (license\.txt)|
 (Makefile)|
 (datastore)|
 (stuff)|
 (org)|
 (setup.py)
 )$
