application: ice-bloc-hdr
version: alpha
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:

## SINGLE FILES
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /google861a6aca749963ad.html
  static_files: static/google861a6aca749963ad.html
  upload: static/google861a6aca749963ad.html

## STATIC
- url: /static
  static_dir: static
  expiration: "1d"

## IMAGES
- url: /images
  static_dir: static/images
  expiration: "7d"

## BUTTONS
- url: /buttons
  static_dir: static/images/buttons
  expiration: "7d"

## DATA
- url: /data
  static_dir: static/data
  expiration: "1d"

## MAPS
- url: /maps
  static_dir: static/maps
  expiration: "1m"

## FONTS
- url: /fonts
  static_dir: static/fonts
  expiration: "7d"

- url: /fonts/(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.eot)
  expiration: "7d"

- url: /fonts/(.*\.woff)
  mime_type: application/x-font-woff
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.woff)
  expiration: "7d"

- url: /fonts/(.*\.ttf)
  mime_type: font/truetype
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.ttf)
  expiration: "7d"

- url: /fonts/(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.(svg|svgz))
  expiration: "7d"

## EDGE CACHE
- url: /remote-sensing/.*
  script: edge-proxy.py

## ADMIN
- url: /cron/.*
  script: cron.py
  login: admin
  
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

## ALL OTHER
- url: .*
  script: main.py

## IGNORE
skip_files: |
 ^(.*/)?(
 (#.*#)|
 (.*~)|
 (.*\.bat)|
 (.*\.xcf)|
 (.*\.rar)|
 (.*\.zip)|
 (.*\.gz)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (static/debug/.*)|
 (static/stuff/.*)|
 (templates/debug/.*)|
 (tests/.*)|
 (docs/.*)|
 (.*\.markdown)|
 (license\.txt)|
 (Makefile)|
 (datastore)|
 (stuff)|
 (org)|
 (setup.py)
 )$
