

## zoom layer 1
# cp ../trans.512.png arc-mask-1-0-0.png
# cp ../trans.512.png arc-mask-1-0-1.png
# cp ../trans.512.png arc-mask-1-0-2.png
# cp ../trans.512.png arc-mask-1-0-3.png
# cp ../trans.512.png arc-mask-1-1-0.png
# cp ../trans.512.png arc-mask-1-1-3.png
# cp ../trans.512.png arc-mask-1-2-0.png
# cp ../trans.512.png arc-mask-1-2-3.png
# cp ../trans.512.png arc-mask-3-0-0.png
# cp ../trans.512.png arc-mask-3-0-1.png
# cp ../trans.512.png arc-mask-3-0-2.png
# cp ../trans.512.png arc-mask-3-0-3.png

wget -O arc-mask-1-0-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=0&TILEROW=0&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-1-0-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=0&TILEROW=0&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-1-1-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=0&TILEROW=1&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-1-1-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=0&TILEROW=1&TILECOL=1&FORMAT=image%2Fpng"

## zoom layer 2 zoom-row-col
wget -O arc-mask-2-0-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=0&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-2-0-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=0&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-2-0-2.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=0&TILECOL=2&FORMAT=image%2Fpng"
wget -O arc-mask-2-0-3.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=0&TILECOL=3&FORMAT=image%2Fpng"
wget -O arc-mask-2-1-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=1&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-2-1-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=1&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-2-1-2.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=1&TILECOL=2&FORMAT=image%2Fpng"
wget -O arc-mask-2-1-3.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=1&TILECOL=3&FORMAT=image%2Fpng"
wget -O arc-mask-2-2-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=2&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-2-2-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=2&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-2-2-2.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=2&TILECOL=2&FORMAT=image%2Fpng"
wget -O arc-mask-2-2-3.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=2&TILECOL=3&FORMAT=image%2Fpng"
wget -O arc-mask-2-3-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=3&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-2-3-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=3&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-2-3-2.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=3&TILECOL=2&FORMAT=image%2Fpng"
wget -O arc-mask-2-3-3.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=1&TILEROW=3&TILECOL=3&FORMAT=image%2Fpng"

## zoom layer 2 zoom-row-col
wget -O arc-mask-3-0-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=0&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-3-0-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=0&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-3-0-2.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=0&TILECOL=2&FORMAT=image%2Fpng"
wget -O arc-mask-3-0-3.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=0&TILECOL=3&FORMAT=image%2Fpng"
wget -O arc-mask-3-0-4.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=0&TILECOL=4&FORMAT=image%2Fpng"
wget -O arc-mask-3-0-5.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=0&TILECOL=5&FORMAT=image%2Fpng"
wget -O arc-mask-3-0-6.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=0&TILECOL=6&FORMAT=image%2Fpng"
wget -O arc-mask-3-0-7.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=0&TILECOL=7&FORMAT=image%2Fpng"
wget -O arc-mask-3-1-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=1&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-3-1-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=1&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-3-1-2.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=1&TILECOL=2&FORMAT=image%2Fpng"
wget -O arc-mask-3-1-3.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=1&TILECOL=3&FORMAT=image%2Fpng"
wget -O arc-mask-3-1-4.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=1&TILECOL=4&FORMAT=image%2Fpng"
wget -O arc-mask-3-1-5.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=1&TILECOL=5&FORMAT=image%2Fpng"
wget -O arc-mask-3-1-6.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=1&TILECOL=6&FORMAT=image%2Fpng"
wget -O arc-mask-3-1-7.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=1&TILECOL=7&FORMAT=image%2Fpng"
wget -O arc-mask-3-2-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=2&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-3-2-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=2&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-3-2-2.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=2&TILECOL=2&FORMAT=image%2Fpng"
wget -O arc-mask-3-2-3.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=2&TILECOL=3&FORMAT=image%2Fpng"
wget -O arc-mask-3-2-4.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=2&TILECOL=4&FORMAT=image%2Fpng"
wget -O arc-mask-3-2-5.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=2&TILECOL=5&FORMAT=image%2Fpng"
wget -O arc-mask-3-2-6.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=2&TILECOL=6&FORMAT=image%2Fpng"
wget -O arc-mask-3-2-7.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=2&TILECOL=7&FORMAT=image%2Fpng"
wget -O arc-mask-3-3-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=3&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-3-3-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=3&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-3-3-2.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=3&TILECOL=2&FORMAT=image%2Fpng"
wget -O arc-mask-3-3-3.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=3&TILECOL=3&FORMAT=image%2Fpng"
wget -O arc-mask-3-3-4.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=3&TILECOL=4&FORMAT=image%2Fpng"
wget -O arc-mask-3-3-5.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=3&TILECOL=5&FORMAT=image%2Fpng"
wget -O arc-mask-3-3-6.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=3&TILECOL=6&FORMAT=image%2Fpng"
wget -O arc-mask-3-3-7.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=3&TILECOL=7&FORMAT=image%2Fpng"
wget -O arc-mask-3-4-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=4&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-3-4-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=4&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-3-4-2.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=4&TILECOL=2&FORMAT=image%2Fpng"
wget -O arc-mask-3-4-3.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=4&TILECOL=3&FORMAT=image%2Fpng"
wget -O arc-mask-3-4-4.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=4&TILECOL=4&FORMAT=image%2Fpng"
wget -O arc-mask-3-4-5.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=4&TILECOL=5&FORMAT=image%2Fpng"
wget -O arc-mask-3-4-6.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=4&TILECOL=6&FORMAT=image%2Fpng"
wget -O arc-mask-3-4-7.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=4&TILECOL=7&FORMAT=image%2Fpng"
wget -O arc-mask-3-5-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=5&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-3-5-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=5&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-3-5-2.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=5&TILECOL=2&FORMAT=image%2Fpng"
wget -O arc-mask-3-5-3.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=5&TILECOL=3&FORMAT=image%2Fpng"
wget -O arc-mask-3-5-4.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=5&TILECOL=4&FORMAT=image%2Fpng"
wget -O arc-mask-3-5-5.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=5&TILECOL=5&FORMAT=image%2Fpng"
wget -O arc-mask-3-5-6.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=5&TILECOL=6&FORMAT=image%2Fpng"
wget -O arc-mask-3-5-7.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=5&TILECOL=7&FORMAT=image%2Fpng"
wget -O arc-mask-3-6-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=6&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-3-6-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=6&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-3-6-2.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=6&TILECOL=2&FORMAT=image%2Fpng"
wget -O arc-mask-3-6-3.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=6&TILECOL=3&FORMAT=image%2Fpng"
wget -O arc-mask-3-6-4.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=6&TILECOL=4&FORMAT=image%2Fpng"
wget -O arc-mask-3-6-5.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=6&TILECOL=5&FORMAT=image%2Fpng"
wget -O arc-mask-3-6-6.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=6&TILECOL=6&FORMAT=image%2Fpng"
wget -O arc-mask-3-6-7.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=6&TILECOL=7&FORMAT=image%2Fpng"
wget -O arc-mask-3-7-0.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=7&TILECOL=0&FORMAT=image%2Fpng"
wget -O arc-mask-3-7-1.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=7&TILECOL=1&FORMAT=image%2Fpng"
wget -O arc-mask-3-7-2.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=7&TILECOL=2&FORMAT=image%2Fpng"
wget -O arc-mask-3-7-3.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=7&TILECOL=3&FORMAT=image%2Fpng"
wget -O arc-mask-3-7-4.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=7&TILECOL=4&FORMAT=image%2Fpng"
wget -O arc-mask-3-7-5.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=7&TILECOL=5&FORMAT=image%2Fpng"
wget -O arc-mask-3-7-6.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=7&TILECOL=6&FORMAT=image%2Fpng"
wget -O arc-mask-3-7-7.png "https://map1b.vis.earthdata.nasa.gov/wmts-arctic/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=land_water_map&STYLE=&TILEMATRIXSET=EPSG3413_250m&TILEMATRIX=2&TILEROW=7&TILECOL=7&FORMAT=image%2Fpng"
